language: python
python:
    - "3.4"
install:
    - pip install -e src
    - pip install -r src/dev_requirements.txt
before_script:
    - cd src
script:
    - flake8 choo --max-line-length 119
    - isort -c -rc .
    - coverage run -m py.test tests
after_success:
    - coveralls
